apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-event-exporter
    path: kubernetes-event-exporter
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 3.2.15
    helm:
      valuesObject:
        config:
          logLevel: info
          receivers:
          - name: dump
            stdout: {}

  syncPolicy:
    syncOptions:
    - ServerSideApply=true


